version: "3.4"
services:
  proxy:
    image: "nginx:1.20"
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/proxy/nginx.conf
    restart: "unless-stopped"
    container_name: proxy
    networks:
      - backend
  api:
    image: "node:16.13"
    build:
      context: ./api
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ./api:/api
      - /api/node_modules
    restart: "unless-stopped"
    container_name: api
    networks:
      - backend
  db:
    image: "mysql:8"
    ports:
      - "3306:3306"
    env_file:
      - ./db/db.env
    volumes:
      - ./data:/var/lib/mysql
    restart: "unless-stopped"
    container_name: db
    networks:
      - backend
    
networks:
  backend: