version: "3.4"
services:
  proxy:
    image: "nginx:1.20"
    ports:
      - "80:80"
    volumes:
      - /home/master/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
  api:
    image: "barunalim_api:0.1" 
    volumes:
      - /home/master/api:/api
      - /api/node_modules
    networks:
      - backend
  db:
    image: "mariadb:10.4"
    ports:
      - "3306:3306"
    env_file:
      - /home/master/db/db.env
    volumes:
      - /home/master/data:/var/lib/mysql
      - /home/master/db/custom.conf:/etc/mysql/conf.d/custom.cnf
    networks:
      - backend
    
networks:
  backend:
