version: "3.4"
services:
  proxy:
    image: "nginx:1.20"
    volumes:
      - /home/master/nfs/stockalimi_proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
  api:
    image: "stockalimi-api:latest" 
    networks:
      - backend
networks:
  backend:
    external:
      name: barun_gateway_backend
